import { FoodPlace } from "../dataTypes/FoodPlace";

const FoodLocations: FoodPlace[] = [
    {
        id: 1,
        name: "鳥貴族 国立店",
        image: "/torikizoku.jpeg",
        coordinates: [139.4413, 35.6999],
        description: "焼き鳥や串焼きを提供する人気の居酒屋チェーン。",
        link: "https://www.torikizoku.co.jp/",
        cusine: ["japanese", "chinese"],
    },
    {
        id: 2,
        name: "サイゼリヤ 国立店",
        image: "/saizeriya.jpeg",
        coordinates: [139.4416, 35.6997],
        description: "お手頃価格のイタリアンと和風のフュージョン料理。",
        link: "https://www.saizeriya.co.jp/",
        cusine: ["italian", "japanese"],
    },
    {
        id: 3,
        name: "やまと寿司",
        image: "/yamatoSushi.jpeg",
        coordinates: [139.4442, 35.7004],
        description: "キャンパス近くの新鮮で美味しい寿司店。",
        link: "https://tabelog.com/tokyo/A1325/A132503/13046270/",
        cusine: ["japanese"],
    },
    {
        id: 4,
        name: "中華そば とみ田",
        image: "/tomita.jpeg",
        coordinates: [139.4420, 35.7010],
        description: "濃厚な味わいのラーメンとつけ麺で有名。",
        link: "https://tabelog.com/tokyo/A1325/A132503/13053361/",
        cusine: ["japanese"],
    },
    {
        id: 5,
        name: "ブルースカイコーヒー",
        image: "/blueSkyCoffee.jpeg",
        coordinates: [139.4407, 35.6995],
        description: "ハンドドリップコーヒーとペストリーが楽しめる居心地の良いカフェ。",
        link: "https://www.instagram.com/blueskycoffee_tokyo/",
        cusine: ["japanese"],
    },
    {
        id: 6,
        name: "CoCo壱番屋 国立店",
        image: "/cocoIchibanya.jpeg",
        coordinates: [139.4425, 35.6998],
        description: "カスタマイズ可能な日本風カレーで有名。",
        link: "https://www.ichibanya.co.jp/",
        cusine: ["japanese"],
    },
    {
        id: 7,
        name: "スシロー 国立店",
        image: "/sushiro.jpeg",
        coordinates: [139.4389, 35.7023],
        description: "グループにもおすすめの人気回転寿司チェーン。",
        link: "https://www.akindo-sushiro.co.jp/",
        cusine: ["japanese"],
    },
    {
        id: 8,
        name: "ガスト 国立店",
        image: "/gusto.jpeg",
        coordinates: [139.4431, 35.7012],
        description: "和洋食の幅広いメニューを提供するカジュアルダイナー。",
        link: "https://www.skylark.co.jp/gusto/",
        cusine: ["japanese", "western"],
    },
    {
        id: 9,
        name: "Rベーカー 国立店",
        image: "/rbaker.jpeg",
        coordinates: [139.4436, 35.6996],
        description: "新鮮なパンやサンドイッチ、ドリンクが楽しめるベーカリーカフェ。",
        link: "https://www.rbaker.jp/",
        cusine: ["japanese", "western"],
    },
    {
        id: 10,
        name: "インド料理サプナ",
        image: "/sapna.jpeg",
        coordinates: [139.4401, 35.7009],
        description: "地元で人気のインドカレー、ナン、ランチセット。",
        link: "https://sapna.jp/",
        cusine: ["indian"],
    },
    {
        id: 11,
        name: "Genki Shichirin Yakiniku Gyushige 国立店",
        image: "/gyushige.jpeg",
        coordinates: [139.4465, 35.6992],
        description: "国立駅から徒歩2分！お得な価格で和牛焼肉が楽しめる。",
        link: "https://s.tabelog.com/en/tokyo/A1325/A132503/13123456/",
        cusine: ["japanese", "korean"],
    },
    {
        id: 12,
        name: "Shoya 国立店",
        image: "/shoya.jpeg",
        coordinates: [139.4450, 35.6988],
        description: "季節の刺身や煮物、焼き鳥が楽しめる老舗居酒屋。",
        link: "https://s.tabelog.com/en/tokyo/A1325/A132503/13123457/",
        cusine: ["japanese"],
    },
    {
        id: 13,
        name: "INDIVI",
        image: "/indivi.jpeg",
        coordinates: [139.4475, 35.7001],
        description: "日本の四季を取り入れたモダンフレンチのダイニング体験。",
        link: "https://s.tabelog.com/en/tokyo/A1325/A132503/13123458/",
        cusine: ["french"],
    },
    {
        id: 14,
        name: "Bistro vin,marché",
        image: "/bistroVinMarche.jpeg",
        coordinates: [139.4480, 35.6995],
        description: "豊洲市場の新鮮な魚介と厳選ワインを楽しめるビストロ。",
        link: "https://s.tabelog.com/en/tokyo/A1325/A132503/13123459/",
        cusine: ["french", "italian"],
    },
    {
        id: 15,
        name: "焼肉 国立 ゆえ",
        image: "/yakinikuYue.jpeg",
        coordinates: [139.4490, 35.7003],
        description: "A5ランクの黒毛和牛を手頃な価格で提供する焼肉店。",
        link: "https://s.tabelog.com/en/tokyo/A1325/A132503/13123460/",
        cusine: ["japanese", "korean"],
    },
    {
        id: 16,
        name: "自然薯庵 国立店",
        image: "/jinenjoAn.jpeg",
        coordinates: [139.4500, 35.6990],
        description: "香り豊かなそばと京都風おでんが楽しめる居酒屋。",
        link: "https://s.tabelog.com/en/tokyo/A1325/A132503/13123461/",
        cusine: ["japanese"],
    },
    {
        id: 17,
        name: "Organic Garden North",
        image: "/organicGardenNorth.jpeg",
        coordinates: [139.4520, 35.6985],
        description: "国立駅から徒歩3分のオーガニックカフェ。",
        link: "https://www.gardenandcrafts.com/north/",
        cusine: ["vegetarian", "cafe"],
    },
    {
        id: 18,
        name: "E Pronto 西国分寺店",
        image: "/ePronto.jpeg",
        coordinates: [139.4535, 35.6978],
        description: "西国分寺駅前のチェーンカフェ、リーズナブルな価格で提供。",
        link: "https://www.pronto.co.jp/shop/detail?shopid=0X00306827",
        cusine: ["cafe", "italian"],
    },
    {
        id: 19,
        name: "Ota Cafe",
        image: "/otaCafe.jpeg",
        coordinates: [139.4550, 35.6965],
        description: "自然に囲まれた静かなカフェ、リラックスできる空間。",
        link: "http://ota-cafe.com/",
        cusine: ["cafe"],
    },
    {
        id: 20,
        name: "Eggg Cafe",
        image: "/egggCafe.jpeg",
        coordinates: [139.4565, 35.6952],
        description: "オムライスとパンケーキが人気のカフェ、コクブンジ駅から徒歩3分。",
        link: "https://www.eggg.jp/",
        cusine: ["cafe", "japanese"],
    },
];

export default FoodLocations;
